service: caravan-scraper # Matches the name in the AWS Console

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2
  memorySize: 2048
  timeout: 300
  architecture: x86_64

  logs:
    restApi: true # Enable API Gateway logging
    retentionInDays: 14

  endpointType: regional

functions:
  scrapeTeePeeCampgroundTent:
    name: scrapeTeePeeCampgroundTent
    handler: handler.scrapeTeePeeCampgroundTent
    events:
      - http:
          path: scrape/teePeeCampgroundTent
          method: post

  payUncleDuckysTent:
    name: payUncleDuckysTent
    handler: handler.payUncleDuckysTent
    events:
      - http:
          path: pay/uncleDuckysTent
          method: post

  payLeelanauPinesTent:
    name: payLeelanauPinesTent
    handler: handler.payLeelanauPinesTent
    events:
      - http:
          path: pay/leelanauPinesTent
          method: post

  payTeePeeCampgroundTent:
    name: payTeePeeCampgroundTent
    handler: handler.payTeePeeCampgroundTent
    events:
      - http:
          path: pay/teePeeCampgroundTent
          method: post

  payIndianRiverTent:
    name: payIndianRiverTent
    handler: handler.payIndianRiverTent
    events:
      - http:
          path: pay/indianRiverTent
          method: post

  payTouristParkTent:
    name: payTouristParkTent
    handler: handler.payTouristParkTent
    events:
      - http:
          path: pay/touristParkTent
          method: post

  payFortSuperiorTent:
    name: payFortSuperiorTent
    handler: handler.payFortSuperiorTent
    events:
      - http:
          path: pay/fortSuperiorTent
          method: post

  payTimberRidgeTent:
    name: payTimberRidgeTent
    handler: handler.payTimberRidgeTent
    events:
      - http:
          path: pay/timberRidgeTent
          method: post

package:
  patterns:
    - "node_modules/**"
    - "handler.js"
    - "scrapers/**"
    - "payers/**"

resources:
  Resources:
    PayLeelanauPinesTentLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${opt:stage, 'dev'}-payLeelanauPinesTent
        RetentionInDays: 14 # Optional: Set log retention period
      DeletionPolicy: Retain # Prevents log group from being deleted during updates

    PayUncleDuckysTentLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${opt:stage, 'dev'}-payUncleDuckysTent
        RetentionInDays: 14
      DeletionPolicy: Retain

    ScrapeTeePeeCampgroundTentLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${opt:stage, 'dev'}-scrapeTeePeeCampgroundTent
        RetentionInDays: 14
      DeletionPolicy: Retain

    PayTeePeeCampgroundTentLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${opt:stage, 'dev'}-payTeePeeCampgroundTent
        RetentionInDays: 14
      DeletionPolicy: Retain

    PayIndianRiverTentLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${opt:stage, 'dev'}-payIndianRiverTent
        RetentionInDays: 14
      DeletionPolicy: Retain

    PayTouristParkTentLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${opt:stage, 'dev'}-payTouristParkTent
        RetentionInDays: 14
      DeletionPolicy: Retain

    PayFortSuperiorTentLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${opt:stage, 'dev'}-payFortSuperiorTent
        RetentionInDays: 14
      DeletionPolicy: Retain

    PayTimberRidgeTentLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${opt:stage, 'dev'}-payTimberRidgeTent
        RetentionInDays: 14
      DeletionPolicy: Retain
