service: caravan-scraper # Matches the name in the AWS Console

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2
  memorySize: 2048
  timeout: 300
  architecture: x86_64

functions:
  teePeeScraper:
    name: teePeeCampgroundScraper
    handler: handler.scrapeTeePee
    events:
      - http:
          path: scrape/teePeeCampgroundTent
          method: post

  payUncleDuckys:
    name: payUncleDuckysTent
    handler: handler.payUncleDuckys
    events:
      - http:
          path: pay/uncleDuckysTent
          method: post

package:
  patterns:
    - "node_modules/**"
    - "handler.js"
    - "scrapers/**"
