service: caravan-scraper # Matches the name in the AWS Console

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2
  memorySize: 2048
  timeout: 300
  architecture: x86_64

functions:
  scrapeFunction:
    name: caravan-scraper # Explicitly set function name to match AWS Console
    handler: handler.scrapeHandler
    events:
      - http:
          path: scrape
          method: post

package:
  patterns:
    - "node_modules/**"
    - "handler.js"

    # - "node_modules/puppeteer-core/**"
    # - "node_modules/extract-zip/**"
    # - "node_modules/debug/**"
    # - "node_modules/ms/**"
    # - "node_modules/get-stream/**"
