service: caravan-scrapers-lambda
provider:
  name: aws
  region: us-east-2
  architecture: x86_64
  ecr:
    images:
      scrapeFunction:
        path: . # Docker image
  memorySize: 3008 # 10 GB (maximum allowed for Lambda)
  timeout: 180

functions:
  scrapeFunction:
    image:
      uri: 445567091402.dkr.ecr.us-east-2.amazonaws.com/caravan-scrapers:latest
    events:
      - http:
          path: scrape
          method: post
          cors: true # Enable CORS if needed
          async: true
