"""Add date_booked field to trips

Revision ID: 9aa0b1f4a3ef
Revises: 3228e470a0e5
Create Date: 2024-12-30 21:42:58.563279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa0b1f4a3ef'
down_revision = '3228e470a0e5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('trips') as batch_op:
        batch_op.add_column(
            sa.Column('date_booked', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'))
        )

    # If you want to backfill with a specific value for existing rows, use:
    op.execute("UPDATE trips SET date_booked = CURRENT_TIMESTAMP")

    # Remove the server default after the column is populated if desired
    with op.batch_alter_table('trips') as batch_op:
        batch_op.alter_column('date_booked', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('date_booked')

    # ### end Alembic commands ###
