"""Add email to Trip table

Revision ID: c0c9913580e5
Revises: 9aa0b1f4a3ef
Create Date: 2025-01-20 17:43:41.485162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c9913580e5'
down_revision = '9aa0b1f4a3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('booking_address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('cardholder_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('card_number', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('card_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('cvc', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('cvc')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('card_type')
        batch_op.drop_column('card_number')
        batch_op.drop_column('cardholder_name')
        batch_op.drop_column('booking_address')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
