name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main # Replace with your branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          npm run build

      - name: Deploy to S3
        env:
          S3_BUCKET: ${{ secrets.FRONTEND_S3_BUCKET }}
        run: |
          aws s3 sync frontend/build s3://$S3_BUCKET --delete

      - name: Invalidate CloudFront Cache (optional)
        if: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
